export enum RequestStatus {
    PENDING = 'PENDING',
    TRANSFERRING = 'TRANSFERRING',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED'
}

export enum RequestDetailStatus {
    TRANSFERRING = 'TRANSFERRING',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED'
}